export type ProteinStructure = {
  _id: string;
  uniprot_id: string;
  pept_cat: string;
  protlen: number;
  genbank_name_curated: string;
  gene: string;
  product: string;
  note: string;
  protein_id: string;
  mat_pept_id: string;
  reg_id: string;
  uniq_id: string;
  uniprot_match_status: string;
  nt_acc: string;
  acc: string;
  seg: string;
  taxid: number;
  Sort: number;
  Realm: string;
  Subrealm: string;
  Kingdom: string;
  Subkingdom: string;
  Phylum: string;
  Subphylum: string;
  Class: string;
  Subclass: string;
  Order: string;
  Suborder: string;
  Family: string;
  Subfamily: string;
  Genus: string;
  Subgenus: string;
  Species: string;
  Exemplar_or_additional_isolate: string;
  "Virus name(s)": string;
  "Virus name abbreviation(s)": string;
  "Virus isolate designation": string;
  Virus_REFSEQ_accession: string;
  Genome_coverage: string;
  Genome_composition: string;
  Host_source: string;
  host: string;
  genbank_genome_coordinates: string;
  genome_coordinates: string;
  protein_coordinates: string;
  esmfold_log_pLDDT: string;
  esmfold_log_pTM: string;
  colabfold_json_pLDDT: string;
  colabfold_json_pTM: string;
  PC1: string;
  PC2: string;
  PC3: string;
  protein_seq: string;
  structure_seq: string;
  genome_length_bp: number;
};
